name: ci

on:
  push:
    # tags:
    #   - 'v[0-9].[0-9]+.[0-9]+'
    branches:
      - 'main'
env:
  IMAGE: 'rosethorn999/nextjs-docker'
  TAG: 'latest'
  CONTAINER_NAME: 'next80'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.CONTAINER_NAME }}
          image: ${{ env.IMAGE }}:${{ env.TAG }}

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
